---
- name: Create vm server
  hcloud_server:
    name: demo-host-vm
    server_type: cpx11
    image: ubuntu-22.04
    location: fsn1
    placement_group: "{{ placement_group.hcloud_placement_group.name }}"
    ssh_keys:
      - MSMacBook
    firewalls:
      - "{{ fw_ssh_result.hcloud_firewall.name }}"
      - "{{ fw_ping_result.hcloud_firewall.name }}"
    state: present
